# Generated by Django 2.2.4 on 2019-08-27 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.Region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RealClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_time', models.CharField(max_length=5)),
                ('fgm', models.IntegerField(default=0)),
                ('fga', models.IntegerField(default=0)),
                ('twoptm', models.IntegerField(default=0)),
                ('twopta', models.IntegerField(default=0)),
                ('threeptm', models.IntegerField(default=0)),
                ('threepta', models.IntegerField(default=0)),
                ('ftm', models.IntegerField(default=0)),
                ('fta', models.IntegerField(default=0)),
                ('offreb', models.IntegerField(default=0)),
                ('defreb', models.IntegerField(default=0)),
                ('reb', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('fouls', models.IntegerField(default=0)),
                ('plusminus', models.IntegerField(default=0)),
                ('points', models.IntegerField(default=0)),
                ('_fantasy_points', models.IntegerField(blank=True, db_column='fantasy_points', default=0)),
                ('match_round', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.Player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='RealClub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.RealClub'),
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ManyToManyField(to='fantasy.Club'),
        ),
        migrations.AddField(
            model_name='club',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fantasy.UserProfile'),
        ),
        migrations.AddField(
            model_name='club',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.Region'),
        ),
    ]
