# Generated by Django 2.2.4 on 2019-10-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_auto_20190828_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_stat',
            name='opponent',
            field=models.CharField(default='none', max_length=35),
            preserve_default=False,
        ),
    ]
