# Generated by Django 2.2.4 on 2019-10-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_player_stat_opponent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_stat',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.RealClub'),
        ),
    ]
