# Generated by Django 2.2.4 on 2019-10-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_auto_20191014_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_stat',
            name='_fantasy_points',
            field=models.IntegerField(blank=True, db_column='fantasy_points'),
        ),
    ]
