# Generated by Django 2.2.4 on 2019-10-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0005_auto_20191014_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_stat',
            name='_fantasy_points',
        ),
    ]
