# Generated by Django 2.2.4 on 2019-10-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0006_remove_player_stat__fantasy_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_stat',
            name='_fantasy_points',
            field=models.IntegerField(blank=True, db_column='fantasy_points', default=0),
            preserve_default=False,
        ),
    ]
