# Generated by Django 2.2.4 on 2019-10-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0007_player_stat__fantasy_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_stat',
            name='_fantasy_points',
        ),
        migrations.AddField(
            model_name='player_stat',
            name='fantasy_points',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
