# Generated by Django 2.2.4 on 2019-10-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0008_auto_20191014_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player_stat',
            name='fantasy_points',
            field=models.IntegerField(),
        ),
    ]
