# Generated by Django 2.2.4 on 2019-10-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0009_auto_20191014_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player_stat',
            name='fantasy_points',
        ),
    ]
