# Generated by Django 2.2.4 on 2019-10-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0011_player_stat_fantasy_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=7)),
            ],
        ),
        migrations.AlterField(
            model_name='player_stat',
            name='fantasy_points',
            field=models.IntegerField(blank=True),
        ),
    ]
