# Generated by Django 2.2.4 on 2019-10-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0012_auto_20191016_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_five', models.BooleanField()),
                ('sixth_man', models.BooleanField()),
                ('bench_player', models.BooleanField()),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.Club')),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='club',
            field=models.ManyToManyField(blank=True, through='fantasy.ClubMember', to='fantasy.Club'),
        ),
        migrations.AddField(
            model_name='player',
            name='club',
            field=models.ManyToManyField(through='fantasy.ClubMember', to='fantasy.Club')
        ),
        migrations.AddField(
            model_name='clubmember',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.Player'),
        ),
    ]
