# Generated by Django 2.2.4 on 2019-10-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0013_auto_20191020_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='club',
            field=models.ManyToManyField(blank=True, through='fantasy.ClubMember', to='fantasy.Club'),
        ),
    ]
