# Generated by Django 2.2.4 on 2020-02-26 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0014_auto_20191020_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyClub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Player_Stat',
            new_name='PlayerStat',
        ),
        migrations.RemoveField(
            model_name='club',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='club',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='club',
            name='region',
        ),
        migrations.RemoveField(
            model_name='ClubMember',
            name='club',
        ),
        migrations.RemoveField(
            model_name='player',
            name='RealClub',
        ),
        migrations.RemoveField(
            model_name='player',
            name='club',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='region',
        ),
        migrations.AddField(
            model_name='player',
            name='Club',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='fantasy.Club'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playerstat',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fantasy.Club'),
        ),
        migrations.DeleteModel(
            name='RealClub',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.AddField(
            model_name='fantasyclub',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fantasy.UserProfile'),
        ),
        migrations.AddField(
            model_name='ClubMember',
            name='fantasy_club',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='fantasy.FantasyClub'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='fantasy_club',
            field=models.ManyToManyField(blank=True, through='fantasy.ClubMember', to='fantasy.FantasyClub'),
        ),
    ]
