# Generated by Django 3.0.4 on 2020-03-09 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0017_auto_20200304_1050'),
    ]

    operations = [
    ]
